py = "python programming"
up = py.upper()
print(up)
print(py.upper())
low = up.lower()
print(low)
#find()
print(py.find('o'))
print(py.find("amala"))
print(py.find('o', 6,18))
print(py.find('gram', 6,18))
#replace()
print(py.replace("o","s"))
#print(py.replace("o","s",0,5))

